title: Praha Kolovraty
baseurl:
permalink: pretty
markdown: rdiscount
facebookurl: https://www.facebook.com/otevrenamesta
twitterurl: https://www.facebook.com/otevrenamesta
gems:
  - jekyll-sitemap


# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: rada, zastupitelstvo, územníplán, kultura, sport
avail_cats: AKCE, JEDNÁNÍ, PLÁNY, ÚŘEDNÍ_DESKA
avail_filecats: SMLOUVY, ZAPISY, VYKRESY, GRAFIKA, UZAVERKY
